Test math logic
mwismann/math-magicians pull request #6
Opened 2023-03-29 22:12 UTC by gdumani

This pull request includes tests for the following components:
|Component |Test Performed |
|--------|--------|
| App | Renders correctly |
| Home | Renders correctly |
| Header | Renders correctly |
| Calculate | Logic works correctly |
| Operate | Logic works correctly |
| Calculator | Renders correctly and UI works correctly |
| Fetch | Renders correctly |

2023-03-29 22:37 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 
- All tests are passing :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 22:37 UTC, tresorsawasawa commented on src/__tests__/calculate.test.js
> +});
- [ ] As required for the project all the functionalities & scenarios of the `calculate.js` module to be covered using Jest, kindly make sure you add tests scenario to `'+/-'`,  `decimal numbers` (i.e. numbers including `.` e.g. `3.5`, `4.23`,...), etc.

2023-03-29 22:37 UTC, tresorsawasawa commented on src/__tests__/operate.test.js
> +});
- [ ] As required for the project all the functionalities & scenarios of the `operate.js` module to be covered using Jest, kindly make sure you add tests scenario to `%`, `raises an error when dividing number by 0`,....

2023-03-30 01:17 UTC, franclobo approved these changes
Hi @gdumani and @mwismann, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/228702917-ae5a1e6d-7926-4cd7-a155-4baee2969629.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

No linter errors ✔️
Descriptive PR ✔️
Correct Git flow ✔️
Professional ReADME file ✔️
All tests passed 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 13:22 UTC, merged